services:
  - type: web
    plan: free
    name: Auto Rename Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 PandaXAshu.py
    repo: 
    branch: main
    autoDeploy: false
    envVars:
      - key: PORT
        sync: false
      - key: REDEPLOY_URL
        sync: false
